name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cv-compile:latest
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cv-compile:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/cv-compile:buildcache,mode=max

      - name: Run Docker Image
        run: docker run -v ${{ github.workspace }}/CV:/CV ${{ secrets.DOCKER_HUB_USERNAME }}/cv-compile:latest
        
      - name: Commit CV
        run: |
          git config --global user.name "Bot"
          git config --global user.email "Bot@noreply.com"
          git fetch
          git checkout -b temp
          git add -A
          git commit -am "Automated commit"
          git push -u origin temp
          git checkout main
          git merge temp
          git push
          git push origin -d temp
      - name: Publish CV
        run: |
          git checkout -b gh-pages origin/gh-pages
          git checkout main CV/main.pdf
          mv CV/main.pdf docs/main.pdf
          git add docs/main.pdf
          git commit --allow-empty -am "Automated commit"
          git push origin gh-pages
