name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
      - uses: docker/build-push-action@v2
        with:
          tags: cv-compile:latest
          push: false

      - name: Run Docker Image
      - run: docker run -v (pwd)/CV:/CV -ti cv-compile:latest
  
#   push:
#     runs-on: debian:10.3
#     needs: build
    
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Push to Temp Branch
#       - run: |
#           git checkout temp
#           git add -A
#           git commit -m "CV compiled"
#           git push
